Po
ashishkatiyar2404/CL-UI pull request #1
Opened 2022-02-04 10:12 UTC by ashishkatiyar2404

2022-02-04 11:12 UTC, j24m reviewed
Great work , would just like to suggest you to add some margin-left to the  component-sidebar and to the right of the documentation. Use color variables instead of directly using color names or hex-codes. The rest seems good. Code is clean and readable to me .💯

2022-02-04 11:12 UTC, j24m commented on Components/PO/alert.css
> +  border: 1px solid gray;
You need to use color variables everywhere no matter what.

2022-02-04 13:29 UTC, ashishkatiyar2404 commented on Components/PO/alert.css
> +  border: 1px solid gray;
ok. actually, the gray border will remove while doing documentation. That was on purpose.
Yup I will remember this.

2022-02-04 13:31 UTC, ashishkatiyar2404 commented
> Great work , would just like to suggest you to add some margin-left to the component-sidebar and to the right of the documentation. Use color variables instead of directly using color names or hex-codes. The rest seems good. Code is clean and readable to me .💯



> Great work , would just like to suggest you to add some margin-left to the component-sidebar and to the right of the documentation. Use color variables instead of directly using color names or hex-codes. The rest seems good. Code is clean and readable to me .💯



> Great work , would just like to suggest you to add some margin-left to the component-sidebar and to the right of the documentation. Use color variables instead of directly using color names or hex-codes. The rest seems good. Code is clean and readable to me .💯

Sure, Will remember your point😄

2022-02-04 16:25 UTC, m26unkwn approved these changes
Loved the BEM naming stye.

2022-02-04 17:52 UTC, dev-prabhat commented on Components/PO/avatar.css
> +  width: 200px;
try to use rem instead of px (greater than 10px)

2022-02-04 17:56 UTC, dev-prabhat requested changes

2022-02-04 17:56 UTC, dev-prabhat commented on style.css
> +.nav-home a {
use class to give styling to the tag

2022-02-05 17:34 UTC, varun1233 commented on Components/PO/alert.css
> +  color: #004085;
Try Using variables for color.

2022-02-05 17:35 UTC, varun1233 commented on Components/PO/avatar.css
> +  border-radius: 0.5rem;
use px for values less than 1 rem

2022-02-05 17:37 UTC, varun1233 commented on Components/PO/button.css
> +  /* border: 1px solid grey; */
Remove commented code if not required

2022-02-07 09:12 UTC, merged